### ISSUE TITLE
Page dims but nothing is displayed (e.g: help(); Ctrl+?, ...)

### ISSUE THREAD

**Issue by abaitam** [funjs/www-functionaljavascript-com#1]
I am using the REPL on the website from a Mac with Mountain Lion using Chrome 27 (and Safari). When I press Command+Enter on the default expression in the REPL, I get the dialog box. However, if I try: help(); or the splat function (page 2), the screen inside the browser window dims but nothing else is displayed; alert(addArrayElements([1,2]); displays the correct value in a dialog.

**Comment by fogus** [comment]
At the moment the REPL does not show the return results of function calls.  To see results `console.log` and `alert` are the ways.
